name: Ngrok Tunnel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
                - name: ngrok-tunnel
  # You may pin to the exact commit or the version.
  # uses: vmactions/ngrok-tunnel@e28904799027c5dd65566e0179fb8d7097972ea4
  uses: vmactions/ngrok-tunnel@v0.0.1
  with:
    # tcp or http
    protocol: # optional
    # port to forward to
    port: 
          
    - name: Download Ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip
        unzip ngrok.zip

    - name: Authenticate Ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Tunnel
      run: ./ngrok tcp 3000
      
